language: python

python:
  - 3.6

env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=flake8

install:
  - pip install tox flake8
  - pip install -r requirements.txt --use-mirrors

script:
  - tox -e $TOX_ENV
